Reorganiza arquivos
hackathon-da-diversidade/agencia-compromisso pull request #20
Opened 2019-10-14 19:32 UTC by lucasbz

Reorganiza os arquivos separando em codigo de testes e de producao
Atualiza teste  de modelo para rodar setUp e tearDown

2019-10-16 20:09 UTC, ingridmurielem commented
Oi @lucasbz já posso revisar esse PR ?

2019-10-16 22:05 UTC, lucasbz commented
> Oi @lucasbz já posso revisar esse PR ?

Pode sim! Obrigado

2019-10-21 19:53 UTC, AndreiRupertti commented
Levantando um questionamento aqui, não tenho uma opinião formada.
Faz sentido termos um diretório chamado `agenciacompromisso/` dentro de um repositório chamado `agencia-compromisso`? 

Não conheço os padrões do Python, mas o que acham de chamarmos de `source/`

2019-10-23 16:04 UTC, ingridmurielem commented
Eu concordo com o questionamento do @AndreiRupertti podemos ter um src

2019-10-23 16:04 UTC, ingridmurielem requested changes
Poderia alterar o nome do diretório

2019-10-28 21:57 UTC, lucasbz commented
Acabei de atualizar o diretorio para src, rodei a app e parece ter funcionado :)

2019-11-01 19:47 UTC, merged