Adds user
hackathon-da-diversidade/agencia-compromisso pull request #29
Opened 2020-02-05 12:34 UTC by astenstrasser

[x] Adiciona User com os usuários autorizados à acessar a aplicação.
[x] Adiciona endpoint /authorize/{email} para verificação

2020-02-05 13:02 UTC, lucassveloso requested changes

2020-02-05 13:02 UTC, lucassveloso commented on src/main/java/com/thoughtworks/agenciacompromisso/services/UserService.java
> +        List<User> authorized = userRepository.findAll();
Existe a possibilidade de tu criar no próprio repository um findByEmail. Ai não precisa realizar um loop no Java para ver se existe usuário registrado.

2020-02-05 13:02 UTC, lucassveloso commented on src/main/java/com/thoughtworks/agenciacompromisso/controllers/UserController.java
> +            headers.add("Location", "http://localhost:3000/menu");
Aqui é importante não passar o localhost pois depende do ambiente.
Apesar que nesse caso você está passando uma url do client. Acho que a ideia é a API não saber pra onde deve redirecionar quando for autorizado. Nesse caso acho legal só retornar se foi ou não autorizado e o frontend fazer o redirect.

2020-02-06 18:38 UTC, ingridmurielem commented on src/main/java/com/thoughtworks/agenciacompromisso/services/UserService.java
> +        List<User> authorized = userRepository.findAll();
Opa concordo com o @lucassveloso

2020-02-06 18:40 UTC, ingridmurielem approved these changes

2020-02-07 12:28 UTC, lucassveloso approved these changes

2020-02-07 12:28 UTC, merged