[Alexandra] Renames fit-model to candidate
hackathon-da-diversidade/agencia-compromisso pull request #48
Opened 2020-06-09 20:27 UTC by astenstrasser

2020-06-09 21:47 UTC, stephanokrm approved these changes
👍🏻

2020-06-10 12:11 UTC, stephanokrm commented on src/test/java/com/thoughtworks/agenciacompromisso/services/FitModelServiceTest.java
> -    public void shouldThrowExceptionWhenTryingToDeleteCandidateThatDoesNotExist() {
Teste não nivelado.

2020-06-10 12:11 UTC, stephanokrm commented on src/test/java/com/thoughtworks/agenciacompromisso/services/FitModelServiceTest.java
> -    public void shouldDeleteCandidate() {
Teste não nivelado.

2020-06-10 12:12 UTC, stephanokrm requested changes
Alguns testes feitos na tarefa de excluir o candidato não foram nivelados para o arquivo `CandidateControllerTest`, mais especificamente os testes `shouldDeleteCandidate` e o `shouldThrowExceptionWhenTryingToDeleteCandidateThatDoesNotExist`

2020-06-10 12:58 UTC, astenstrasser commented on src/test/java/com/thoughtworks/agenciacompromisso/services/CandidateServiceTest.java
> +    public void shouldDeleteCandidate() {
@stephanokrm são esses dois testes?

2020-06-10 13:13 UTC, stephanokrm commented on src/test/java/com/thoughtworks/agenciacompromisso/services/CandidateServiceTest.java
> +    public void shouldDeleteCandidate() {
@astenstrasser Sim

2020-06-10 20:47 UTC, stephanokrm approved these changes
👍🏻

2020-06-10 20:47 UTC, merged